name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs once a day
  workflow_dispatch: {} # allows manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Rahilyw
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#fff8e7,#ffd166,#ff8c42,#ff5e00&color_dots=#fdf6ec,#ffe8b3,#ffd166,#ffab5e,#ff7f3f&color_animate=#ff5e00
            dist/github-contribution-grid-snake-dark.svg?color_snake=#fff8e7,#ffd166,#ff8c42,#ff5e00&color_dots=#2b1a0e,#5c3a1a,#a35a1e,#e08327,#ffb347&color_animate=#ffb347

      - name: Push output to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
